package pong.game;

import sheep.game.State;
import sheep.input.TouchListener;
import android.graphics.Canvas;
import android.graphics.Color;
import android.view.MotionEvent;

public class TitleScreen extends State implements TouchListener {
	
    private GameLayer gameLayer;
    private int touchX,touchY;
    public final static int WIDTH = 1280;
    public final static int HEIGHT = 690;
    
    public TitleScreen(){
    	gameLayer = new GameLayer();
    	addTouchListener(this);
    }

    public void draw(Canvas can){
    	can.drawColor(Color.BLACK);
    	gameLayer.draw(can, null);
    }
    
    public void update(float dt){
    	gameLayer.update(dt);
    	
    }
    
    /**
	 * Called when the user touches down on the screen.
	 * @param event The event generated by the action.
	 * @return True if the event was consumed, false otherwise.
	 */
	public boolean onTouchDown(MotionEvent event){
		gameLayer.getBall().setMotion(true);
		return true;
	}
	
	/**
	 * Called when the user releases a touch from the screen.
	 * @param event The event generated by the action.
	 * @return True if consumed, false otherwise.
	 */
	public boolean onTouchUp(MotionEvent event){
		return true;
	}
	
	/**
	 * Called when the user drags a touch along the screen.
	 * @param event The event generated by the action.
	 * @return True if consumed, false otherwise.
	 */
	public boolean onTouchMove(MotionEvent event){
		touchX = (int) event.getX();
		touchY = (int) event.getY();
		gameLayer.getPaddle_touch(touchX).move(touchY);
		return true;
	}
}
